services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-dev-container
    volumes:
      - ./src:/home/developer/workspace/src
      - ./build:/home/developer/workspace/build
      - ./build/conan/cache:/home/developer/.conan2
      - ./CMakeLists.txt:/home/developer/workspace/CMakeLists.txt
      - ./conanfile.txt:/home/developer/workspace/conanfile.txt
      - ./.build_env:/home/developer/workspace/.build_env
      - ./logs:/home/developer/workspace/build/bin/logs
      - ./.env:/home/developer/workspace/build/bin/.env
    ports:
      - "2222:22"     # SSH
      - "7777:7777"   # gdbserver
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE   # Required for debugging
    security_opt:
      - seccomp:unconfined  # Required for debugging
