version: '3'

services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-dev-container
    volumes:
      - ./src:/home/developer/workspace/src
      - ./CMakeLists.txt:/home/developer/workspace/CMakeLists.txt
      - ./conanfile.txt:/home/developer/workspace/conanfile.txt
    ports:
      - "2222:22"     # SSH
      - "7777:7777"   # gdbserver
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE   # Required for debugging
    security_opt:
      - seccomp:unconfined  # Required for debugging
